# Generated by Django 5.2.13 on 2026-04-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='anexos/'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='orcamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='prestador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
