# Generated by Django 5.2.13 on 2026-05-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_prestador_alter_chamado_prestador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('aguardando_orcamento', 'Aguardando Orçamento'), ('orcamento_enviado', 'Orçamento Enviado'), ('orcamento_aprovado', 'Orçamento Aprovado'), ('orcamento_reprovado', 'Orçamento Reprovado'), ('em_andamento', 'Em Andamento'), ('resolvido_internamente', 'Resolvido Internamente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=30),
        ),
    ]
