# Generated by Django 5.2.13 on 2026-05-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='inquilino',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='telefone',
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('rural', 'Rural'), ('industrial', 'Industrial')], default='residencial', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
